# Publish Docker image & PyPi package when a GitHub release is made
name: publish

on:
  release:
    types: [published]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: virtool/workflow-tools:${{ github.event.release.tag_name }}